# Generated by Django 5.2.14 on 2026-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('interest', models.CharField(blank=True, max_length=80)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('num', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('deck', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, max_length=80)),
                ('date', models.CharField(blank=True, max_length=40)),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('body', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('num', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('short', models.TextField(blank=True)),
                ('body', models.JSONField(blank=True, default=list)),
                ('formats', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Practice',
                'ordering': ['order', 'num'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('num', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=160)),
                ('italic_title', models.CharField(blank=True, max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('series', models.CharField(blank=True, max_length=120)),
                ('edition', models.CharField(blank=True, max_length=80)),
                ('stamp', models.CharField(blank=True, max_length=16)),
                ('format', models.CharField(blank=True, max_length=80)),
                ('pages', models.CharField(blank=True, max_length=40)),
                ('binding', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(blank=True, max_length=160)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('blurb', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'num'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('num', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('typology', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=12)),
                ('surface', models.CharField(blank=True, max_length=40)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('palette', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'num'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
