# Generated by Django 5.2.14 on 2026-05-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
