# Generated by Django 5.2.14 on 2026-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='retreats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='speaking',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
