# Generated by Django 5.2.14 on 2026-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitesettings_about_sitesettings_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('num', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('italic_title', models.CharField(blank=True, max_length=200)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('lede', models.TextField(blank=True)),
                ('problem', models.JSONField(blank=True, default=list)),
                ('transformation', models.JSONField(blank=True, default=list)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('cadence', models.CharField(blank=True, max_length=120)),
                ('format', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(blank=True, max_length=120)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(default='Apply to this programme', max_length=100)),
                ('cta_to', models.CharField(default='/enquire?subject=programme', max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
