"""Migrate 11 blog posts Eunice provided (29 May) into the JournalPost table.

Idempotent — skips any slug that already exists. Run from backend/:

    .venv/Scripts/python.exe migrate_blogs.py
"""
import os
import sys
import json
import urllib.request
from datetime import datetime, timezone
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env", override=True)

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
import django; django.setup()

from api.models import JournalPost

UNSPLASH_KEY = os.environ.get("UNSPLASH_ACCESS_KEY", "")


def fetch_cover(query):
    """Pull a landscape Unsplash photo for a query. Returns a 1600w URL."""
    if not UNSPLASH_KEY:
        return ""
    url = (
        "https://api.unsplash.com/search/photos"
        f"?query={urllib.parse.quote(query)}"
        "&orientation=landscape&per_page=3&order_by=relevant&content_filter=high"
    )
    req = urllib.request.Request(url, headers={
        "Authorization": f"Client-ID {UNSPLASH_KEY}",
        "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
        if not data.get("results"):
            return ""
        photo = data["results"][0]
        photo_id = photo["urls"]["raw"].split("/photo-")[1].split("?")[0]
        return f"https://images.unsplash.com/photo-{photo_id}?auto=format&fit=crop&w=1600&q=85"
    except Exception as exc:
        print(f"  ! cover fetch failed for {query!r}: {exc}")
        return ""


# === The 11 posts ===
# Each entry: slug, num, title, deck (one-line teaser), section, date display
# string, read_time, cover_query (sent to Unsplash), body list. The body
# uses the `## H2` / `### H3` markdown convention NoteDetail now understands.

POSTS = [
    {
        "slug": "navigate-unexpected-life-changes",
        "num": "013",
        "title": "How to Navigate Unexpected Life Changes",
        "deck": "You did not ask for this season. How to rebuild your life after loss and unexpected change, even when you do not know what you are building yet.",
        "section": "Wellbeing",
        "date": "October 2026",
        "read_time": "9 min",
        "cover_query": "woman walking misty path autumn reflective",
        "body": [
            "## The Uncharted Territory",
            "Maybe you lost someone. Maybe a relationship ended. Maybe the career you built, the identity you wore, the future you had mapped out quietly or suddenly stopped being available to you. And now you are here, in a place you never planned to be, trying to figure out how to move forward when you cannot yet see where forward is.",
            "This is one of the hardest places a person can find themselves. Not because something has gone catastrophically wrong, but because nothing in your old toolkit quite works here. The strategies that served you before, the plans, the timelines, the drive to just push through, they do not translate into this terrain.",
            "So what does? That is what this blog post is about. Not a five-step fix. Not toxic positivity dressed up as wisdom. Just honest, grounded things that actually help when you are moving through a life you did not plan.",
            "## Understand the Ground You Are Standing On",
            "Before you can navigate a transition, it helps to know what kind of terrain you are actually in. There is a phase, and most people who have been through significant change will recognise it, that sits between what was and what is coming. The old life has ended. The new one has not yet taken shape. You are in the middle, and the middle has no clear landmarks.",
            "This phase is disorienting by design. It is supposed to unsettle you, because what is being asked of you here is not to perform or produce but to shed. Old identities, old assumptions, old versions of what you thought your life was supposed to look like. That shedding takes time, and it rarely feels graceful while it is happening.",
            "The first thing that helps is simply naming it. You are not failing. You are not falling apart. You are in transition. And transition, by its very nature, is uncomfortable. That discomfort is not a signal to panic, it is a signal that something real is happening.",
            "## Stop Waiting to Feel Ready",
            "One of the most common things my clients say in the middle of a life transition is: I will start moving when I feel more ready. When the grief lifts a little. When I have more clarity. When things settle down. When I have a new job.",
            "But here is the truth: readiness rarely arrives before movement. More often, it arrives because of it. You do not need to have it figured out before you take a step. You do not need to know what you are building before you pick up the first piece. The clarity you are waiting for tends to come through small, honest, imperfect actions, not before.",
            "This does not mean rushing. It means being willing to move, even slowly, even uncertainly, without waiting for a green light that may not come until you are already on your way.",
            "## Grieve What Needs to Be Grieved",
            "Transitions involve loss. Even the ones that are ultimately leading you somewhere better. The relationship. The career. The version of yourself you thought you would be by now. The future you had already started to picture. These things deserve to be grieved properly, not quickly, not efficiently.",
            "Skipping grief does not make you stronger or more resilient. It makes you someone who is carrying unprocessed loss into the next chapter, your second season, where it will eventually show up uninvited. Grief is not the opposite of moving forward. It is part of how you move forward. Let it have its place. Let it be as messy and nonlinear as it actually is. You are not behind because you are still feeling it.",
            "## Anchor Yourself in What Is Still True",
            "When everything shifts, it is easy to feel like you have lost yourself entirely. But you have not. Underneath the circumstances, underneath the loss and the uncertainty, there are things that are still fundamentally you. A value you have always held. A way of showing up in the world that has not changed. Something that still brings you a small measure of peace or meaning, even in a hard season.",
            "Find those things. Stay close to them. They are your anchor while everything else is still finding its shape. You are not starting from nothing; you are starting from everything you have already lived, learned and survived.",
            "## Let People In",
            "I hope you're still reading. We are not designed to navigate significant life transitions alone. We need people who understand not to fix us or hand us answers, but to witness what we are going through and remind us that we are not invisible in it.",
            "This might be a trusted friend. A professional. A community of people who have walked something similar. Whatever form it takes, do not make the mistake of thinking that needing support is a weakness. It is one of the most honest and courageous things you can do in a hard season, and trust me, here I've been there. Isolation makes everything harder. A real, seen, supported connection makes the unbearable more bearable and the possible more visible.",
            "## Trust That You Are Being Shaped, Not Broken",
            "Here is something I have come to believe deeply, from my own experience and from walking alongside others through theirs: the seasons we do not plan are often the ones that shape us most profoundly.",
            "Not because suffering is automatically good. It is not. But when life strips away the structure we built around ourselves, what remains is more real. More true. And from that more honest place, something new becomes possible, something that could not have emerged from the comfortable, planned version of your life. You do not have to see what that is yet. You do not have to know what you are building. You just have to stay in the process honestly, patiently, and with the quiet trust that you are not being undone.",
            "You are **becoming.**",
            "## You Do Not Have to Do This Alone",
            "If you are in this season right now, navigating grief, rebuilding after loss, standing at a crossroads with no clear map, I want you to know that there is a space being created specifically for you.",
            "My Second Season Programme is a group coaching programme for successful women moving through significant life transitions. It is a structured, supported space to process what you have been carrying, reconnect with who you truly are, and begin moving toward your second season with clarity, confidence, and intention, surrounded by a community of women who genuinely understand.",
            "Stay tuned. If something in you is saying this is the right time, trust that instinct. This second season was never planned. Your second season is not the end of your story. It is the beginning of the most honest chapter yet.",
        ],
    },
    {
        "slug": "navigate-life-you-did-not-plan",
        "num": "014",
        "title": "How to Navigate the Life You Did Not Plan",
        "deck": "Honest, grounded things that actually help when you are moving through a life you did not plan.",
        "section": "Mindset",
        "date": "September 2026",
        "read_time": "9 min",
        "cover_query": "woman walking foggy path purposeful contemplative",
        "body": [
            "You did not ask for this season. Maybe you lost someone. Maybe a relationship ended. Maybe the career you built, the identity you wore, the future you had mapped out quietly or suddenly stopped being available to you. And now you are here, in a place you never planned to be, trying to figure out how to move forward when you cannot yet see where forward is.",
            "This is one of the hardest places a person can find themselves. Not because something has gone catastrophically wrong, but because nothing in your old toolkit quite works here. The strategies that served you before, the plans, the timelines, the drive to just push through, they do not translate into this terrain.",
            "So what does? That is what this post is about. Not a five-step fix. Not toxic positivity dressed up as wisdom. Just honest, grounded things that actually help when you are moving through a life you did not plan.",
            "## Understand the Ground You Are Standing On",
            "Before you can navigate a transition, it helps to know what kind of terrain you are actually in.",
            "There is a phase, and most people who have been through significant change will recognise it, that sits between what was and what is coming. The old life has ended. The new one has not yet taken shape. You are in the middle, and the middle has no clear landmarks.",
            "This phase is disorienting by design. It is supposed to unsettle you, because what is being asked of you here is not to perform or produce but to shed. Old identities, old assumptions, old versions of what you thought your life was supposed to look like. That shedding takes time, and it rarely feels graceful while it is happening.",
            "The first thing that helps is simply naming it. You are not failing. You are not falling apart. You are in transition. And transition, by its very nature, is uncomfortable. That discomfort is not a signal to panic, it is a signal that something real is happening.",
            "## Stop Waiting to Feel Ready",
            "One of the most common things my clients say in the middle of a life transition is: I will start moving when I feel more ready. When the grief lifts a little. When I have more clarity. When things settle down.",
            "But here is the truth: readiness rarely arrives before movement. More often, it arrives because of it.",
            "You do not need to have it figured out before you take a step. You do not need to know what you are building before you pick up the first piece. The clarity you are waiting for tends to come through small, honest, imperfect actions, not before.",
            "This does not mean rushing. It means being willing to move, even slowly, even uncertainly, without waiting for a green light that may not come until you are already on your way.",
            "## Grieve What Needs to Be Grieved",
            "Transitions involve loss. Even the ones that are ultimately leading you somewhere better.",
            "The relationship. The career. The version of yourself you thought you would be by now. The future you had already started to picture. These things deserve to be grieved properly, not quickly, not efficiently.",
            "Skipping grief does not make you stronger or more resilient. It makes you someone who is carrying unprocessed loss into the next chapter, where it will eventually show up uninvited.",
            "Grief is not the opposite of moving forward. It is part of how you move forward. Let it have its place. Let it be as messy and nonlinear as it actually is. You are not behind because you are still feeling it.",
            "## Anchor Yourself in What Is Still True",
            "When everything shifts, it is easy to feel like you have lost yourself entirely. But you have not. Underneath the circumstances, underneath the loss and the uncertainty, there are things that are still fundamentally you.",
            "A value you have always held. A way of showing up in the world that has not changed. Something that still brings you a small measure of peace or meaning, even in a hard season.",
            "Find those things. Stay close to them. They are your anchor while everything else is still finding its shape. You are not starting from nothing; you are starting from everything you have already lived, learned and survived.",
            "## Let People In",
            "We are not designed to navigate significant life transitions alone. We need people who understand not to fix us or hand us answers, but to witness what we are going through and remind us that we are not invisible in it.",
            "This might be a trusted friend. A therapist. A community of people who have walked something similar. Whatever form it takes, do not make the mistake of thinking that needing support is a weakness. It is one of the most honest and courageous things you can do in a hard season.",
            "Isolation makes everything harder. A real, seen, supported connection makes the unbearable more bearable and the possible more visible.",
            "## Trust That You Are Being Shaped, Not Broken",
            "Here is something I have come to believe deeply, from my own experience and from walking alongside others through theirs: the seasons we do not plan are often the ones that shape us most profoundly.",
            "Not because suffering is automatically good. It is not. But when life strips away the structure we built around ourselves, what remains is more real. More true. And from that more honest place, something new becomes possible, something that could not have emerged from the comfortable, planned version of your life.",
            "You do not have to see what that is yet. You do not have to know what you are building. You just have to stay in the process honestly, patiently, and with the quiet trust that you are not being undone.",
            "**You are becoming.**",
            "## You Do Not Have to Do This Alone",
            "If you are in this season right now, navigating grief, rebuilding after loss, standing at a crossroads with no clear map, I want you to know that there is a space being created specifically for you.",
            "The Second Season Programme is a group coaching programme for women moving through significant life transitions. It is a structured, supported space to process what you have been carrying, reconnect with who you truly are, and begin moving toward your next chapter with clarity and intention, surrounded by a community of women who genuinely understand.",
            "The doors are opening soon. If something in you is saying this is the right time, trust that instinct. Your second season is not the end of your story. It is the beginning of the most honest chapter yet.",
        ],
    },
    {
        "slug": "how-grief-actually-works",
        "num": "015",
        "title": "How Grief Actually Works: You're Not Back at Square One",
        "deck": "Grief is not linear, it comes in waves. Understanding why can be the difference between surviving it and being consumed by it.",
        "section": "Wellbeing",
        "date": "August 2026",
        "read_time": "8 min",
        "cover_query": "ocean waves soft morning melancholic peaceful",
        "body": [
            "You thought you were doing better, and then one Tuesday morning, out of nowhere, it hit you again, the weight of it, the absence, the ache, and suddenly it felt like you were back at the very beginning, but you're not back at square one. This is how grief actually works.",
            "Although it can feel that way. And that feeling is one of the most confusing, isolating parts of grief that almost nobody talks about honestly. Grief is not a straight line. It never was. Understanding why can be the difference between surviving it and being consumed by it.",
            "## The Myth of the Stages",
            "### Where the idea came from",
            "Most of us grew up hearing about the five stages of grief: denial, anger, bargaining, depression, and acceptance. The psychiatrist Elisabeth Kübler-Ross developed this model in 1969. It was never meant to be a roadmap for how grief should unfold.",
            "She observed patterns which she noticed in terminally ill patients facing their own deaths. Somewhere along the way, it became a **prescription**.",
            "The problem is that prescriptions for grief are dangerous. When you believe grief should move through predictable stages, you start measuring yourself against a standard that was never designed for you. And when you inevitably don't match it, you conclude there is something wrong with you. There isn't.",
            "And in 2019, David Kessler, the grief expert, added the sixth stage of grief, Finding Meaning, in his book of the same name. In this book, David offers a perspective on how grief can be transformed into meaning, which in turn leads to healing. Remember, grief is personal, and it must be experienced to be understood.",
            "### What grief actually looks like",
            "Grief is better understood as waves than stages. Some waves are massive and knock you off your feet. Others are small and manageable. Some arrive when you expect them on anniversaries, milestones, and holidays. Others come from nowhere: a smell, a song, a stranger who laughs the way they did.",
            "Researchers now describe this as the oscillating nature of grief. You move between loss-orientation, facing the grief directly, and restoration-orientation, rebuilding your life and sense of self. Both are necessary. Both are healthy. Neither cancels the other out.",
            "## Why We Try to Rush It",
            "### The social pressure to 'move on'",
            "Society is deeply uncomfortable with grief. After a socially acceptable mourning period usually measured in weeks, sometimes in months, there is enormous pressure, often unspoken, to return to normal. To be okay. To stop being sad in ways that make other people uncomfortable.",
            "This pressure can come from well-meaning friends and family. It can come from workplace culture. It can come from the internal belief that needing too long means you're weak or broken. Whatever its source, the effect is the same: you learn to perform wellness before you've actually arrived there.",
            "### The cost of the performed healing",
            "When you rush grief or are rushed through it, you don't skip it. You defer it. Grief has a way of re-surfacing eventually, often in disguised forms: anxiety, numbness, overworking, disconnection, short tempers, or a vague sense that something is permanently missing. The body and mind will always find a way to process what was never allowed to be felt.",
            "Allowing grief to be non-linear is not wallowing. It is not a weakness. It is the only honest, natural and sustainable way through.",
            "## What to Do When the Wave Comes Back",
            "### Name it without judgement",
            "When grief resurfaces unexpectedly, the first instinct is often to fight it. To tell yourself you shouldn't be feeling this, that you were doing so well. Instead, try naming it simply and without judgement: 'A wave is here.' That's all. You don't need to analyse it or assign meaning to its return. You just need to acknowledge it.",
            "### Let it move through",
            "Grief that is resisted tends to persist. Grief that is allowed is felt fully, however painful, and tends to pass. This doesn't mean you have to be consumed by it. It means creating small windows of time when you let yourself feel what you feel, without distraction or apology. Even fifteen minutes of genuine presence with the emotion can release what hours of suppression cannot.",
            "### Return to your anchors",
            "After the wave, you need anchors, those things that ground you in the present and remind you that life continues. These might be people, places, routines, or practices. They don't need to be dramatic. A morning walk, a cup of tea, a phone call with someone who loves you. Anchors don't erase the grief. They hold you steady while it passes.",
            "## A Word on Time",
            "People say time heals. It's not quite right. What time does is give you more experience, more context, and more distance. Healing, the actual integration of loss into a life that still has meaning, is something you actively participate in. Time is the **container**. You are the work.",
            "Whenever the grief returns, even in smaller waves, remember it's not a setback. This is not evidence that you are broken or stuck. **This is grief doing what grief does.**",
            "And you show up for yourself through another wave; that is exactly what healing looks like. I cover all this in my 1:1 coaching programme, which I designed specifically for high-achieving women who've lost loved ones.",
        ],
    },
    {
        "slug": "the-art-of-resilience",
        "num": "016",
        "title": "The Art of Resilience: How to Rebuild Strength, Meaning, and Momentum After Adversity",
        "deck": "Real resilience is not about bouncing back to who you were. It is about learning how to rebuild differently.",
        "section": "Wellbeing",
        "date": "July 2026",
        "read_time": "7 min",
        "cover_query": "lone tree dry landscape resilient strong",
        "body": [
            "Resilience has become one of the most overused words of our time. It's often reduced to *just keep going* or *stay positive*. But real resilience, the kind that actually sustains a life, a business, and a sense of self, is far more nuanced. Resilience is not about bouncing back to who you were. It's about learning how to _rebuild differently_.",
            "## Resilience Is a Practice, Not a Personality Trait",
            "Contrary to popular belief, resilient people aren't born tougher; they've simply learned to respond to challenges with intention rather than reactivity.",
            "Think of resilience like architecture. When a building collapses, you don't reconstruct it using the same faulty blueprint. You reassess the foundation, strengthen weak points, and then redesign for longevity.",
            "True resilience works the same way. It's not brute force endurance. It's a thoughtful adaptation.",
            "## When Resilience Turns Into Burnout: The Cost of Pushing Too Hard",
            "Many high-achieving women pride themselves on being resilient because they've survived _a lot_. Loss. Burnout. Reinvention. Leadership pressure.",
            "But here's the uncomfortable truth: Survival without integration eventually leads to exhaustion.",
            "If resilience is built solely on grit, it becomes brittle. Strong on the outside. Fragile underneath.",
            "The most resilient individuals don't just endure hardship, they _process it_. They create space to grieve, to question, and to redefine success on their own terms.",
            "## The Three Pillars of Sustainable Resilience",
            "From studying psychology, leadership, and lived experience, sustainable resilience rests on three often overlooked pillars:",
            "### 1. Emotional Honesty",
            "Resilience begins with acknowledging what hurts, without rushing to fix it. Suppressed emotions don't disappear; they resurface as fatigue, cynicism, or disconnection.",
            "### 2. Meaningful Reframing",
            "Adversity doesn't automatically make us stronger. Reflection does. When we consciously extract meaning from hardship, it stops defining us and starts informing us.",
            "### 3. Intentional Redesign",
            "Resilient lives are designed, not defaulted into. This includes boundaries, energy management, supportive environments, and aligned goals, not just ambition.",
            "## Why Resilience Is an Art, Not a Formula",
            "There is no universal resilience checklist. What restores one person may deplete another. This is why resilience is an art. It requires discernment, self-trust, and ongoing recalibration.",
            "Just like art evolves with the seasons, resilience changes and grows with the seasons, too. What you needed to survive may not be what you need to thrive. And that's not failure. That's growth.",
            "In my 1:1 coaching consulting, I guide women through designing sustainable resilience strategies for both life and business after adversity.",
            "## A Forward-Thinking Reframe",
            "The future of resilience isn't about enduring more. It's about _living better_ with clarity, depth, and sustainability.",
            "Resilience isn't the absence of breaking. It's the wisdom to rebuild with intention. And that, quietly and powerfully, changes everything.",
        ],
    },
    {
        "slug": "unexpected-outcome-in-life",
        "num": "017",
        "title": "An Unexpected Outcome in Life",
        "deck": "Sometimes a well-planned life can lead you somewhere you never expected to go.",
        "section": "Mindset",
        "date": "June 2026",
        "read_time": "8 min",
        "cover_query": "winding road forest dawn forked path",
        "body": [
            "Sometimes a well-planned life can lead you somewhere you never expected to go. Life can throw curveballs, and these sudden critical events can turn our personal and work lives upside down in an instant. Understanding how these surprises affect our feelings, drives and actions is important.",
            "## You did everything right.",
            "You studied hard, made sensible choices, built a stable career, and stayed on track. You followed the plan, maybe your own plan, maybe one you quietly inherited from the expectations around you. Either way, you showed up, you worked hard, and you kept going.",
            "And then one day, you looked up from all that doing and realised this is not where you thought you would end up.",
            "Not in a dramatic, everything-fell-apart way. Just in a quiet, unsettling way. Like walking into a room and forgetting why you came in, only the room is your life. That moment can stop you completely.",
            "## The Plan Was Real. So Is This.",
            "Here is something important to say first: the plan was not wrong. The years of effort were not wasted. The choices that brought you here were real, and they mattered. You were not foolish for following them.",
            "But life has a way of moving underneath us while we are busy executing our strategy. Priorities shift. People change. Losses happen. What once lit us up quietly fades. And sometimes the very structure we built to protect ourselves becomes the thing that is keeping us small.",
            "A well-planned life can deliver everything it promised: security, stability, a certain kind of success and still leave you with a feeling that something essential is missing. That is not ingratitude. That is honesty.",
            "## The Unexpected Outcome Is Not the Problem",
            "We are conditioned to see unexpected outcomes as failures. Detours. Evidence that something went wrong.",
            "But what if the unexpected outcome is not a breakdown, but a breakthrough, trying to get your attention?",
            "Think about the people who discovered their true calling only after losing a job they thought they could not live without. Or the ones who found genuine peace only after a relationship they had planned their whole life around came to a sudden end. Or those who stepped into the most meaningful work of their lives precisely because the original plan stopped working.",
            "The unexpected outcome is rarely the end of the story. More often, it is the beginning of the more honest one.",
            "## You Already Have the Answer",
            "Here is what I know from working with people through life's most disorienting crossroads, including mine: the confusion you feel in the face of an unexpected outcome is not a sign that you are lost. It is a sign that you are paying attention.",
            "Something in you already knows that this moment is significant. Something in you is asking a question you have been afraid to answer. What do I actually want?",
            "That question can feel dangerous when you have spent years building a life around a different answer. But it is also the most important question you will ever ask yourself, and you are the only one who can answer it.",
            "No coach, no mentor, no perfectly curated plan can tell you what your life is supposed to mean. That knowledge lives in you. It always has. Sometimes it just takes an unexpected outcome to create enough space for you to hear it.",
            "## What to Do When You Are Here",
            "If you are standing in the middle of an unexpected outcome right now, here are a few things worth sitting with.",
            "**Give yourself permission to be unsettled.** You do not need to immediately reframe this into something positive. It is okay to feel disoriented. The disorientation is part of the process, not a problem to fix.",
            "**Resist the urge to rebuild the old plan immediately.** The instinct when things feel uncertain is to rush back to the familiar. But this moment is inviting you to pause before you do. What you rebuild next deserves to come from a more honest place than urgency.",
            "**Ask what this has revealed, not just what it has taken.** Unexpected outcomes always carry information. They show you what you were holding onto too tightly. They show you what you actually value when the structure falls away. They show you who you are underneath the plan.",
            "**Trust that you are more capable of navigating this than it feels like you are right now.** You have already moved through difficult things. You have already adapted, recovered, and rebuilt. This is not the first time life has surprised you, and you have not yet failed to find your way through.",
            "## The Life That Wants to Emerge",
            "A well-planned life is not the same as a fully lived one. The plan is a map, useful and necessary, but the territory of your actual life is always bigger, messier, and more interesting than any map can capture.",
            "When an unexpected outcome arrives, it is an invitation to stop looking at the map and start looking at the ground beneath your feet. To ask not just where you were trying to go, but where you actually are and what might be possible from here.",
            "You do not need a new plan right away. You need presence. Honesty. A willingness to stay with the question a little longer than is comfortable.",
            "Because the life that wants to emerge from this moment is not something that needs to be forced or figured out all at once. It needs to be allowed. And that begins with trusting that you are not the plan, not the outcomes, not the external markers of success; you are the one who holds the answer. You always were.",
        ],
    },
    {
        "slug": "the-void-phase",
        "num": "018",
        "title": "The Void Phase: Why You Feel Stuck, Lost and Unable to Think Clearly",
        "deck": "This is the stage of adversity no one talks about — the moment where everything has happened, but nothing makes sense.",
        "section": "Mindset",
        "date": "May 2026",
        "read_time": "6 min",
        "cover_query": "woman foggy day quiet contemplative blurred soft",
        "body": [
            "It's not the initial shock, not the visible grief, nor even the rebuilding. It's the space in between. The moment where everything has happened, but nothing makes sense. This is the stage of adversity no one talks about, and why you feel stuck, lost and unable to think clearly. This is the moment in adversity that no one prepares you for.",
            "## The Void Phase",
            "This is where your mind refuses to compute what your life has become. Where clarity disappears. Where your thoughts feel heavy, slow, or simply absent. You try to think, plan, or even imagine a future, but your brain won't cooperate. This isn't failure. This is your nervous system protecting you.",
            "In The Void, your brain is overwhelmed. It downregulates to survive. What feels like being stuck is often cognitive shutdown, a response to emotional overload. And here's the truth most people miss: You are not _meant_ to figure your life out at this stage, just go with the flow.",
            "You are meant to stabilise. But how do you move forward when you can't think clearly? Don't leap. You **anchor**.",
            "### This is how you can start:",
            "**1. Reduce the pressure to understand everything.** Clarity will come later. For now, focus on what is manageable today.",
            "**2. Return to the body.** When the mind is foggy, the body becomes your compass. Gentle movement, breathwork, or even sitting in stillness helps regulate your system.",
            "**3. Simplify decisions.** This is not the season for big life choices. Protect your energy by minimising the decisions you _have_ to make.",
            "**4. Create micro-structure.** Small, predictable routines rebuild safety. Think: wake, eat, walk, rest and repeat.",
            "**5. Borrow belief.** If you cannot see your future, trust that your current state is temporary. This void phase is a bridge, not a destination.",
            "## You don't have to make sense of everything on your own.",
            "If you're finding yourself in this in-between space and craving gentle guidance, _Second Season_, my programme launching soon, is a journey created for moments exactly like this, where healing comes before clarity, and small steps matter more than big leaps.",
            "The Void Phase is uncomfortable because it feels like nothing is happening. But something is. You are recalibrating. Processing. You are quietly preparing for the next version of your life. Even if you can't see it yet.",
        ],
    },
    {
        "slug": "shifting-your-mindset-for-abundance",
        "num": "019",
        "title": "Shifting Your Mindset for Abundance",
        "deck": "Abundance isn't something you chase. It's something you allow.",
        "section": "Mindset",
        "date": "April 2026",
        "read_time": "9 min",
        "cover_query": "sunrise open horizon expansion peaceful golden",
        "body": [
            "Shifting your mindset for abundance is the inner work that changes everything. There comes a moment, quiet, almost unnoticeable, when you realise your life is no longer limited by circumstances, but by your thinking. Not your talent, your experience or even your past. It's your mindset. Because abundance isn't something you chase. It's something you allow.",
            "## Shifting Your Mindset For Abundance Isn't External, It's Internal",
            "Most high-achieving women don't struggle with effort. They struggle with _permission_. Permission to want more, to receive more and permission to live beyond survival mode. You can have the strategy, the plan, the network and still feel stuck. Why? Because if your internal world is wired for scarcity, you will unconsciously reject abundance even when it's right in front of you.",
            "Scarcity sounds like: I have to work harder to deserve more. There's not enough space for me. If I slow down, everything will fall apart.",
            "Abundance sounds like: Opportunities expand as I do. There is space for me at every level. I create results from alignment, not exhaustion.",
            "This is not about positive thinking. This is about _identity recalibration_.",
            "## The Hidden Cost of a Scarcity Mindset",
            "Scarcity is subtle and dangerously convincing. It dresses itself as responsibility, logic, even humility. But underneath it? It's fear. Fear of loss, of judgment. Fear of not being enough, even when you've achieved everything on paper.",
            "And here's the hard truth: Scarcity keeps you overworking, overgiving, and under-receiving. It creates a life that looks successful but feels heavy. So if you've been doing all the right things but still feel like something is missing, it's not a strategy problem. It's a mindset ceiling.",
            "## Abundance Requires Expansion, Not Addition",
            "Most people try to add abundance into their lives. More clients, more income and more opportunities. But abundance doesn't come from adding more. It comes from _becoming more available_ for what already exists.",
            "Think of it like this: If your nervous system is only comfortable receiving at a certain level, anything beyond that will feel unsafe, even if it's what you say you want. So you delay. You overthink. You self-sabotage subtly. Not because you're broken, but because your system hasn't caught up with your vision.",
            "## How to Shift Your Mindset for Abundance",
            "This is where the real work begins, not on the outside, but within.",
            "### 1. Upgrade Your Identity",
            "Stop asking, _How do I get more?_ Instead, ask, _Who do I need to become to hold more?_ Abundance is an identity, not an outcome. The woman who operates in abundance: makes decisions from trust, not fear. Sets boundaries without guilt. Receives without over-explaining her worth. You don't wait to become her. You practice being her now.",
            "### 2. Build Evidence for Expansion",
            "Your brain believes what it sees repeatedly. So instead of waiting for massive breakthroughs, start collecting small evidence daily: moments where things worked in your favour, unexpected opportunities, support you didn't have to fight for. This trains your mind to _recognise abundance_ rather than filter it out.",
            "### 3. Redefine Effort and Worth",
            "One of the biggest mindset traps? Believing that abundance must be earned through struggle. But what if ease is not laziness but alignment? What if the next level of your life requires _less force and more flow?_ This doesn't mean doing nothing. It means doing what matters, without burning yourself out to prove your value.",
            "### 4. Expand Your Receiving Capacity",
            "This is where most people unconsciously block abundance. Ask yourself honestly: Do I deflect compliments? Do I undercharge or overdeliver? Do I feel uncomfortable when things feel too good?",
            "Receiving is a skill. Start small: Say thank you without justification. Accept support without guilt. Let things be easy without questioning them. This is how you rewire your relationship with abundance.",
            "### 5. Surround Yourself with Expansion",
            "Your environment either reinforces scarcity or normalises abundance. If you are constantly surrounded by people who play small, fear growth, or question ambition, you will shrink without realising it. But when you're in rooms where expansion is normal? You rise. Not because you're trying harder, but because your standards have shifted.",
            "## The Real Shift: From Control to Trust",
            "At its core, shifting your mindset for abundance is not about control. It's about trust. Trust that you are capable of holding more. You are allowed to want more. You don't have to prove your worth through exhaustion. And most importantly, trust that abundance is not something you have to chase endlessly. It's something you **align** with again and again.",
            "## Your Next Season Requires a New Mindset",
            "You're not who you were five years ago. Your capacity has grown, your vision has evolved. Your standards are higher. So the question is no longer: _Can I create abundance?_ The question now is: _Am I willing to think, choose, and show up differently to sustain it?_",
            "Because the life you want is not waiting for you to work harder. It's waiting for you to expand.",
            "Abundance is not reserved for the lucky, the loud, or the already successful. It belongs to the woman who decides internally that she is no longer available to be limited. And on that decision? That's where everything begins.",
        ],
    },
    {
        "slug": "redefining-your-purpose-after-major-life-change",
        "num": "020",
        "title": "Redefining Your Purpose After a Major Life Change",
        "deck": "Purpose is not something you find like a missing object. It's something you redefine.",
        "section": "Mindset",
        "date": "March 2026",
        "read_time": "8 min",
        "cover_query": "open notebook morning sunlight new beginning quiet",
        "body": [
            "There comes a moment in life when everything that you built your identity around shifts. Not gradually. Not politely, but all at once. A loss. A burnout or unexpected health challenge. A life event you never saw coming, and suddenly the question isn't What do I want next? Instead, it becomes: Who am I now? This is the space that requires you to redefine your purpose after a major life change.",
            "## The Myth of Finding Your Purpose",
            "Purpose is not something you find like a missing object. It's something you redefine. Most high-achieving women have spent years building a life that made sense on paper. Career. Relationships. Identity. Structure. These major life changes disrupt the structure you've built. And here's the uncomfortable truth: What once gave your life meaning may no longer fit who you are becoming. That's not failure. That's evolution.",
            "## When Life Breaks the Old Identity",
            "After a major life change, there is often an invisible identity collapse. You're no longer the partner you were. The version of you that thrived in that career. The person who once handled everything with ease.",
            "And yet, you're not fully the new you either. This creates a tension that most people try to rush out of. And here's a perspective shift: This space is not empty. It's creative. It's where your next level of purpose is being formed quietly, beneath the surface.",
            "## Redefining Purpose Requires Letting Go First",
            "This is where many people get stuck. They try to redefine their purpose while still holding onto their old identity. That's like trying to redecorate a room that's already full. And at some point, you have to ask: What version of me am I still trying to hold onto? What expectations no longer feel aligned? What am I afraid to release?",
            "I would like to think that your purpose isn't built on what's familiar. It's built on what's true now.",
            "## The Shift: From Achievement to Alignment",
            "Before any major life change, your purpose is often driven by achievement, external validation, productivity, proving something. After a major life change, everything recalibrates. Purpose becomes less about doing more and more and more about being aligned.",
            "Aligned with your energy. Your values. Your emotional truth. Your capacity. And that's where things get clearer; alignment often asks you to slow down while the world tells you to speed up.",
            "## A More Honest Way to Rebuild Your Purpose",
            "Redefining your purpose isn't about having a grand vision immediately; it starts smaller than that.",
            "### 1. Notice What Still Feels Meaningful",
            "Even in the hardest seasons, there are small things that feel grounding. Conversations. Creativity. Helping others. Quiet moments. That's data. Your purpose leaves clues.",
            "### 2. Pay Attention to What You No Longer Tolerate",
            "Your standards change after life changes. What once felt acceptable now feels draining. That's not you being difficult. That's you becoming more discerning.",
            "### 3. At the Start, Let Purpose Be Fluid",
            "Here's a thought that might challenge you: What if your next purpose isn't permanent? What if it's a season? Taking the pressure off allows something more authentic to emerge.",
            "### 4. Build From Lived Experience",
            "The most powerful purpose is not theoretical. It's lived. When you've walked through grief, burnout, health challenge and divorce, rebuilding becomes the foundation for impact. Not because it was easy. But because it was real.",
            "## The Quiet Rebuilding",
            "Redefining your purpose can feel: Slow. Uncertain. Uncomfortable. Lonely at times.",
            "There's no applause in this phase. No clear milestones, just small, internal shifts that eventually change everything. This is where depth is built. And depth creates unshakable purpose.",
            "## A Different Kind of Success",
            "If you're in this season, maybe success is no longer about how much you can carry; it's about how aligned your life feels when you wake up each day. Maybe purpose is no longer about proving your worth. It's about expressing who you've become.",
            "## The Truth Most People Won't Say",
            "You won't go back to who you were. And trying to will only delay what's waiting for you. There's an opportunity: You get to consciously choose who you become next. Not by default. Not by expectation. It's by designing your new life. I call this well-being by design.",
            "Redefining your purpose after major life changes isn't about starting over. It's about starting from experience. From depth. The truth. From a version of you that now sees life differently.",
            "And that? Is not a **setback**. That's **an advantage.**",
        ],
    },
    {
        "slug": "when-life-breaks-open-quiet-rebuilding",
        "num": "021",
        "title": "When Life Breaks Open (Part 2): The Quiet Rebuilding No One Talks About",
        "deck": "There are moments when everything falls apart, when the world goes strangely quiet. This is the part no one prepares you for.",
        "section": "Wellbeing",
        "date": "February 2026",
        "read_time": "10 min",
        "cover_query": "woman in light filled room healing peaceful interior",
        "body": [
            "When life breaks open, there are moments when everything falls apart, when the world goes strangely quiet. The initial shock has passed. The messages slow down. People assume you're doing better. But internally, something deeper is happening. You are standing in a space between who you were and who you are becoming. And this is the part no one really prepares you for.",
            "Not the grief itself, burnout, divorce, diagnosis or the identity collapse. But what comes after? The _quiet_ rebuilding.",
            "## The Season After the Storm",
            "When life breaks open, the first phase is often survival. You move through the days as best as you can. Doing what needs to be done. You carry responsibilities even when your energy feels depleted. But eventually, something shifts. The world continues to move, and slowly you begin to notice deeper questions rising within.",
            "Questions that are impossible to ignore, for example: _What does my life look like now? Who am I becoming? What truly matters to me now? And how do I move forward?_",
            "These are not surface-level questions. They are identity questions; they signal the beginning of a new season.",
            "## The Uncomfortable Space Between Lives",
            "Many women describe this phase as a feeling of being suspended between two lives. The old life has ended. But the new one hasn't fully taken shape yet. You are no longer the woman who existed before the loss, the burnout, the divorce, or the diagnosis. Yet you are still rediscovering who you are now.",
            "It can feel unsettling. Sometimes lonely. But it is also deeply transformative.",
            "This period can take up to a few years; everyone is different, because in this in-between space, something powerful happens: You begin to see your life more clearly. The expectations you once carried. The roles you played. The pace you lived at. The capabilities you had. You start questioning things that once felt normal. And slowly, almost quietly, your priorities begin to shift.",
            "## Why Many Women Try to Rush This Season",
            "In the world we live in today, there is often pressure to bounce back. To move forward quickly, rebuild life exactly as it was before. To carry on as life goes on. But the real transformation rarely works that way. When life breaks open, it often reveals parts of our lives that were misaligned long before the crisis occurred.",
            "Burnout may expose years of overgiving. Divorce may reveal unmet needs. Grief may bring clarity about what truly matters.",
            "These realisations take time to integrate. And yet this slower season is often where the most meaningful growth occurs. Not through dramatic reinvention. But through quiet reflection. Through asking better questions. Through allowing yourself the space to evolve.",
            "## The Role Our Environment Plays in Rebuilding",
            "Our homes are reflections of who we are and the lives that we have lived. These environments take on a new significance for those of us who are coping with grief through the loss of a loved one, divorce, unexpected diagnosis, or a significant life change, as we are surrounded by objects and spaces that retain the memories of a former time. However, redesigning our home can be a powerful and hopeful step that helps us transition into a new season of life, as we move through the healing process.",
            "After my husband passed away, I realised something that many women overlook. The way we had been living no longer reflected the life I was stepping into. The rhythms of the home belonged to a different chapter. The spaces held memories of a life that had changed forever.",
            "Our homes are not neutral spaces. And as someone who had spent years designing living and working spaces for clients, I knew the important role that environments play in our daily lives. They influence how we feel. How we think. How we process change. During major life transitions, our environment can either support our healing or quietly hold us in the past. Sometimes the smallest shifts can recreate space for something new. I see my home as my silent partner in my healing process, and I hope you do too.",
            "Rearranging furniture in a room. A corner redesigned. A new rhythm within the home. These are not just aesthetic changes; they are symbolic ones for your sacred space. They signal that life is evolving and that we are allowed to evolve with it.",
            "## The Seasons of Life, and Change Is Inevitable",
            "One of the ideas that has shaped my thinking the most is this: Life is seasonal. Just as nature moves through cycles of winter, spring, summer, and autumn, our lives also move through seasons of expansion, rest, loss, and renewal.",
            "Yet many of us try to live as though everything should remain constant. We build lives designed for stability. But growth rarely follows a straight line. There are seasons of deep clarity. And seasons of uncertainty. Seasons where everything feels aligned. And seasons where life quietly dismantles what no longer serves us. None of these seasons is a mistake. They are part of the human experience.",
            "## The Beginning of a Different Kind of Life",
            "When life breaks open, it often invites us to rebuild with greater intention. Not by recreating the past. But by designing a life that supports who we are now. For some, this might mean redefining success. Changing how you spend your time. Letting go of roles that no longer fit. Or creating an environment that nurtures the life you are rebuilding.",
            "These shifts rarely happen overnight. But over time, when you prioritise your well-being, something beautiful begins to emerge: Clarity. Confidence. Strength. A deeper understanding of what truly matters. And perhaps most importantly, a quieter but more grounded sense of self.",
            "## When Life Breaks Open, It's A Gentle Invitation",
            "If you find yourself in the in-between season right now, the space where life has broken open but the future still feels uncertain, know that you are not alone. This phase is not a sign that you are lost. It is often the very place where transformation begins.",
            "In recent years, talking to other women and my own experiences led me to create The Seasons of Life Home Method™, a framework that explores how our environments and lives can evolve alongside the seasons we move through. Because when we learn to honour the season we are in, something shifts. We stop rushing. We stop comparing our timeline to others. And we begin to rebuild our lives in ways that are more intentional, more supportive, and more aligned with who we are becoming.",
            "Sometimes life breaks open in ways we never expected. But within that opening lies the possibility of a life aligned and designed with deeper meaning. A life shaped not by circumstance alone, but by conscious choice. And that may be the beginning of something far more powerful than we ever imagined.",
        ],
    },
    {
        "slug": "when-life-breaks-open-redefines-everything",
        "num": "022",
        "title": "When Life Breaks Open, the Season That Redefines Everything",
        "deck": "For many high-achieving women, this is the season no one prepares you for — when life breaks open and does not break down.",
        "section": "Wellbeing",
        "date": "January 2026",
        "read_time": "10 min",
        "cover_query": "broken light streaming through window dawn transformation",
        "body": [
            "There are moments in life when everything you thought was solid suddenly isn't. The ground shifts. The story changes. And the version of you that once knew exactly who you are quietly disappears. For many high-achieving women, this is the season that no one prepares you for. When life breaks open is the season that redefines everything for you.",
            "It arrives through grief. Through burnout that creeps in after years of holding everything together. Through a divorce that dismantles the life you carefully built. Through a diagnosis that redraws the map of your future. Or through an identity collapse, when you wake up one day and realise the life you're living no longer fits who you've become.",
            "I call it the season of _Inner and Outer Realignment_, when life breaks open and does not break down.",
            "There is a difference. Because when life breaks open, everything hidden inside you begins to surface. The grief you postponed, the exhaustion you ignored, and the questions you were too busy to ask. It is messy. Uncomfortable. And often deeply lonely. But it is also the beginning of something most people never talk about. A profound redefinition of who you are.",
            "## Navigating Major Life Transitions: Grief, Burnout and Identity Shifts",
            "What makes these seasons so disorienting is that they don't just change circumstances. They change identity too.",
            "You are no longer the wife. The partner. The person who once had a predictable future. You are no longer the woman who could carry endless responsibility without consequence.",
            "Burnout strips away the illusion of strength. Grief dismantles certainty. Divorce rewrites belonging. Diagnosis interrupts the illusion of control.",
            "### The Silent Collapse of the Old Life",
            "And suddenly, the life you built no longer reflects the woman you are becoming. No one really tells you what to do at this moment. During major life transitions, our identity often shifts in ways we never expected.",
            "Because society prefers quick recoveries and inspirational endings. But the real transformation rarely looks neat. Often, it begins in the quiet moment when you sit in your own home and realise something startling. Everything has changed. The life around you no longer matches the life within you.",
            "## Redesigning Your Home for Major Life Transitions",
            "After my husband passed away, I realised something that surprised me. The way we had been living the rhythms of the home, the spaces we used, the energy of the environment, no longer served the woman I was at that moment and the woman I was becoming.",
            "The house still reflected a life that had ended. The routines belonged to a version of me that no longer existed. And as someone who had spent years as an interior designer, I couldn't ignore the truth that became obvious to me.",
            "Our environments are silent storytellers. But we rarely talk about this space that holds us while we're healing. They hold memories. They hold identities. They hold the life chapters of where we've been and how we've lived. But sometimes they also hold us in the past that no longer exists.",
            "And when life breaks open, you begin to see **everything differently**. The spaces you once loved feel unfamiliar. The structure of your life no longer makes sense. You start asking deeper questions: Who am I now? What kind of life do I want to create from here? What direction do I take from here?",
            "These questions rarely arrive during easy seasons. They arrive during the collapse, the difficult time.",
            "## The Hidden Gift of These Seasons",
            "Here is the quiet truth I have come to believe. The seasons that dismantle us are often the same seasons that invite us to redesign our lives with far greater intention. Not the life we inherited. Not the life we performed. But the life that genuinely **aligns** with who we are now.",
            "Grief can deepen your capacity for meaning. Burnout can force you to redefine success. Divorce can reconnect you with independence. Diagnosis can sharpen your clarity about what truly matters.",
            "These seasons strip away illusion. And while that process is painful, it can also be incredibly clarifying. Because when life breaks open, it creates space. The space to rebuild differently. Space to honour the woman you are becoming. Space to recreate a life that supports your emotional and spiritual well-being, not just your responsibilities. Space to rebuild the life and business you love.",
            "## Redesigning Life for the Season You're In",
            "One of the most important realisations I had during my own journey was this: Life is seasonal. Just as nature moves through cycles of winter, spring, summer and autumn, we move through emotional and psychological seasons too. But most of us design our homes and our lives as if everything should remain the same forever.",
            "We build structures for stability. Yet life inevitably changes. Loss happens. Growth happens. Transformation happens. And when it does, the environments we live in, physically and emotionally, must evolve with us. Not because something is wrong. But because something new is emerging.",
            "## When Life Breaks Open, Something New Begins",
            "If you are in a season of grief, burnout, divorce, diagnosis or identity collapse, it may feel like life has fallen apart. But what if something else is happening too? What if this moment is not simply an ending, but an opening?",
            "An opening to question old definitions of success. An opening to redesign a life that reflects who you are now. An opening to recreate environments both internally and externally that genuinely support your well-being.",
            "Because when life breaks open, it does not just reveal pain. It reveals possibilities.",
            "And sometimes the most powerful thing we can do is to pause, breathe, and begin asking a different question: _If I were redesigning my life for this season, what would it look like now?_",
            "Because when we learn to honour our seasons, something remarkable happens. Life doesn't just break open. It begins to unfold.",
        ],
    },
    {
        "slug": "emotional-strength-foundation-of-life-management",
        "num": "023",
        "title": "Why Emotional Strength Is the Foundation of Life Management",
        "deck": "No life management system works without emotional strength beneath it.",
        "section": "Wellbeing",
        "date": "December 2025",
        "read_time": "8 min",
        "cover_query": "meditation quiet morning candle serene calm strength",
        "body": [
            "Most conversations about life management revolve around tools: better routines, sharper focus, stronger discipline, tighter boundaries. Planners, productivity systems, morning rituals. All useful, yet for many high-achieving women, something still feels off.",
            "You're doing everything right, but life still feels heavy. Decision-making feels draining. Small disruptions throw you off more than they should. Rest doesn't quite restore you.",
            "Here's the uncomfortable truth we don't talk about enough: **No life management system works without emotional strength beneath it.**",
            "Emotional strength isn't a soft add-on to life management. It _is_ the **foundation.**",
            "## Why Life Management Fails Without Emotional Strength",
            "If life management were purely about structure, then the most organised people would also be the most fulfilled. But we know that isn't true.",
            "You can have a perfectly planned week, and still feel overwhelmed. Clear goals and still feel stuck. Strong discipline, and still feel emotionally exhausted.",
            "Why? Because _emotional capacity determines how well you can use structure._",
            "When emotional reserves are low: Boundaries feel harder to maintain. Decisions feel heavier than they should. Time pressure feels personal. Even small setbacks feel destabilising. Emotional depletion turns normal life demands into emotional stress.",
            "## The Nervous System: The Missing Link In Life Management",
            "Here's what most productivity conversations ignore: how to manage your emotions. Life management is a nervous system issue before it's a time issue. Emotional strength is the quiet foundation of what I call true life management, not time management.",
            "When your nervous system is dysregulated: Everything feels urgent. Rest feels unproductive. You default to overdoing or withdrawing. You manage life in survival mode.",
            "Emotional strength management allows the nervous system to settle. From that settled place, priorities become clearer, boundaries feel more natural, and effort becomes more sustainable. This is why slowing down often creates better momentum than pushing harder, a paradox many high performers resist until burnout forces the lesson.",
            "## Emotional Strength Creates Internal Order",
            "Emotional strength is the foundation of true life management. As someone with interior design experience, I see emotional strength the way I see a well-designed home. An organised space isn't just about aesthetics; it's about flow and functionality that enhance well-being, productivity, and emotional connection, and that tells a personal story.",
            "### Emotional strength creates the same effect internally:",
            "Thoughts become less cluttered. Decisions feel less dramatic. You stop over-managing what doesn't matter. You conserve energy for what matters.",
            "Without emotional order, life feels noisy. With it, even busy seasons feel more navigable.",
            "## Why High-Achieving Women Especially Need This Shift",
            "High-achieving women are often praised for their ability to cope well. Being strong. Holding it together. But coping isn't the same as internal support. Many of the women I work with are incredibly capable yet emotionally overextended. They've mastered external management while neglecting internal capacity, and eventually, the gap shows up as burnout, numbness, unfulfilled or a quiet loss of joy.",
            "Emotional strength allows ambition to coexist with well-being without one cannibalising the other.",
            "## Building Emotional Strength Is a Practice, Not a Personality Trait",
            "This is the hopeful part. Emotional strength isn't something you either have or don't. It's something you _build_.",
            "It grows when you: Create space to process rather than rush past emotions. Learn to pause before reacting. Honour rest as strategic, not indulgent. Design your life to support your nervous system, not constantly override it.",
            "Small, intentional shifts compound, just as any other life management skill does.",
            "## The New Definition of Being",
            "True life management isn't a perfectly executed routine. It's the ability to move through life with: Emotional steadiness. Self-trust. Sustainable energy. Compassion for your own humanity.",
            "When emotional strength is present, life doesn't need to be micromanaged. It flows with more ease, even when it's challenging. And perhaps that's the most refined form of well-being there is, not controlling life, but having the inner capacity to meet it.",
        ],
    },
]


# === Run ===
created = 0
skipped = 0
for i, post in enumerate(POSTS):
    if JournalPost.objects.filter(slug=post["slug"]).exists():
        print(f"  · skip  {post['slug']:60} (already exists)")
        skipped += 1
        continue
    cover = fetch_cover(post["cover_query"])
    JournalPost.objects.create(
        slug=post["slug"],
        num=post["num"],
        title=post["title"],
        deck=post["deck"],
        section=post["section"],
        date=post["date"],
        read_time=post["read_time"],
        is_premium=False,
        cover=cover,
        body=post["body"],
        published=True,
        order=100 + i,  # push imported posts after the existing seeded ones
    )
    print(f"  ✓ added {post['slug']:60} cover={'yes' if cover else 'NO'}")
    created += 1

print(f"\n{created} created · {skipped} skipped · total now: {JournalPost.objects.count()}")
