/* Regenerates public/sitemap.xml from the live route list — same source
 * of truth as scripts/prerender.mjs.  Pulls dynamic slugs from the Django
 * API when reachable; falls back to siteData.js otherwise.
 *
 * Run from repo root:  node scripts/build-sitemap.mjs
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '..')

const SITE = 'https://eunicedecampi.com'
const API_BASE = process.env.SITEMAP_API_BASE || 'http://127.0.0.1:8000/api'

// Static routes — priority + lastmod tuned by importance
const STATIC = [
  { path: '/',           priority: 1.0,  changefreq: 'weekly' },
  { path: '/about',      priority: 0.9,  changefreq: 'monthly' },
  { path: '/practice',   priority: 0.9,  changefreq: 'monthly' },
  { path: '/programmes', priority: 0.9,  changefreq: 'monthly' },
  { path: '/journal',    priority: 0.8,  changefreq: 'weekly' },
  { path: '/shop',       priority: 0.7,  changefreq: 'monthly' },
  { path: '/membership', priority: 0.7,  changefreq: 'monthly' },
  { path: '/retreats',   priority: 0.8,  changefreq: 'monthly' },
  { path: '/speaking',   priority: 0.7,  changefreq: 'monthly' },
  { path: '/enquire',    priority: 0.6,  changefreq: 'yearly' },
  { path: '/privacy',    priority: 0.3,  changefreq: 'yearly' },
  { path: '/cookies',    priority: 0.3,  changefreq: 'yearly' },
  { path: '/terms',      priority: 0.3,  changefreq: 'yearly' },
]

const FALLBACK_SLUGS = {
  practice:   ['interiors', 'mindset', 'writing', 'circle'],
  journal:    ['the-room-as-a-collaborator', 'second-season', 'inner-architecture', 'quiet-report-q1', 'letters-to-women-rebuilding'],
  shop:       ['second-season-workbook', 'quiet-report-q1', 'letters-pamphlet', 'sanctuary-bedroom-guide', 'annual-print-edition', 'morning-ledger'],
  programmes: ['reinvention', 'considered-recovery', 'interior-wellbeing-audit'],
}

async function apiSlugs(endpoint) {
  try {
    const res = await fetch(`${API_BASE}/${endpoint}/`, { signal: AbortSignal.timeout(3000) })
    if (!res.ok) return null
    const data = await res.json()
    const items = Array.isArray(data) ? data : (data.results || [])
    return items.map((x) => x.slug).filter(Boolean)
  } catch { return null }
}

async function main() {
  // Pull live slugs when the API is reachable; fall back otherwise.
  const live = {
    practice:   (await apiSlugs('practice')),
    journal:    (await apiSlugs('journal')),
    shop:       (await apiSlugs('shop')),
    programmes: (await apiSlugs('programmes')),
  }
  const slugs = Object.fromEntries(
    Object.entries(FALLBACK_SLUGS).map(([k, fb]) => [k, (live[k] && live[k].length) ? live[k] : fb])
  )

  const today = new Date().toISOString().slice(0, 10)
  const urls = [
    ...STATIC,
    ...slugs.practice.map((s)   => ({ path: `/practice/${s}`,   priority: 0.7, changefreq: 'monthly' })),
    ...slugs.journal.map((s)    => ({ path: `/journal/${s}`,    priority: 0.6, changefreq: 'monthly' })),
    ...slugs.shop.map((s)       => ({ path: `/shop/${s}`,       priority: 0.6, changefreq: 'monthly' })),
    ...slugs.programmes.map((s) => ({ path: `/programmes/${s}`, priority: 0.8, changefreq: 'monthly' })),
  ]

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/build-sitemap.mjs · ${today} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${SITE}${u.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority.toFixed(1)}</priority>
  </url>`).join('\n')}
</urlset>
`
  const out = path.join(REPO_ROOT, 'public', 'sitemap.xml')
  await fs.writeFile(out, xml)
  console.log(`Wrote ${urls.length} URLs to ${path.relative(REPO_ROOT, out)}`)
  console.log(`  Static: ${STATIC.length}`)
  console.log(`  Practice: ${slugs.practice.length}`)
  console.log(`  Journal:  ${slugs.journal.length}`)
  console.log(`  Shop:     ${slugs.shop.length}`)
  console.log(`  Programmes: ${slugs.programmes.length}`)
}

main().catch((err) => { console.error(err); process.exit(1) })
